name: enough_ascii_art
description: Generates ASCII art using image to ASCII, FIGlet text banner
  support and emoticon to text conversions.
version: 1.1.0
homepage: https://github.com/Enough-Software/enough_ascii_art

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  characters: ^1.1.0
  image: ^4.0.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
