name: enough_ascii_art
description: Generates ASCII art using image to ASCII, FIGlet text banner support and emoticon to text conversions.
version: 1.0.0
homepage: https://github.com/Enough-Software/enough_ascii_art

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  image: ^3.0.5
  characters: ^1.1.0
  
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
